### ISSUE TITLE
Update to reflect new socket.io

### ISSUE THREAD

**Issue by parj** [threedaymonk/node-websocket-demo#1]
I had stumbled across your nice & simple demo, but it failed due to the new socket io library. 

main.js should now just have the line
var socket = io.connect();

server.js should now have the line
socket.sockets.on('connection'
instead of 
socket.on('

**Comment by parj** [comment]
If you allow me to push to a branch I can push the changes so that you can review and merge changes

**Comment by parj** [comment]
For now forked and pushed to master - https://github.com/parj/node-websocket-demo

**Comment by threedaymonk** [comment]
Thanks. I've pulled your change, and made it serve `socket.io.js` locally to ensure it gets the right version.
